namespace EDFlib
{
    /// <summary>
    /// Exception generated by the EDF library.
    /// </summary>
    public class EDFException : Exception
    {
        private int errNum;

        public EDFException(int errNum, string msg) : base(msg)
        {
            this.errNum = errNum;
        }

        public int ErrNum
        {
            get { return errNum; }
        }
    }
}