namespace BBD.BodyMonitor.Configuration
{
    /// <summary>
    /// Configuration options for machine learning features.
    /// </summary>
    public class MachineLearningOptions
    {
        /// <summary>
        /// Gets or sets an array of machine learning profiles.
        /// </summary>
        /// <remarks>
        /// Each MLProfile likely defines settings for a specific machine learning model or task.
        /// </remarks>
        public MLProfile[] Profiles { get; set; } = new MLProfile[0];
        /// <summary>
        /// Gets or sets a value indicating whether to include headers in CSV output files generated by machine learning processes.
        /// </summary>
        public bool CSVHeaders { get; set; } = false;
        /// <summary>
        /// Gets or sets a value indicating whether to generate MetaBorg configuration files.
        /// </summary>
        /// <remarks>
        /// MetaBorg (mbconfig) is likely a specific tool or framework used in conjunction with the application.
        /// </remarks>
        public bool GenerateMBConfigs { get; set; } = false;
    }
}