@BBD.BodyMonitor.API_HostAddress = https://0.0.0.0:7061
# For more info on HTTP files go to https://aka.ms/vs/httpfile
@BBD.BodyMonitor.Web_HostAddress = https://localhost:7061

# Start data acquisition
GET {{BBD.BodyMonitor.Web_HostAddress}}/DataAcquisition/start

###

# Stop data acquisition
GET {{BBD.BodyMonitor.Web_HostAddress}}/DataAcquisition/stop

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/system/getconfig

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/system/getsysteminformation

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP09/Subject_/Subject_AndrasFuchs/Subject_AndrasFuchs/200
GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP09/Subject_/Subject_AndrasFuchs/Subject_AndrasFuchs/1000
GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP09/Subject_/Subject_AndrasFuchs/Subject_AndrasFuchs/3500
GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP10/Subject_/Subject_AndrasFuchs/Subject_AndrasFuchs/3500

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP09/Subject_/Subject_TimeaNagy/Subject_TimeaNagy/3500

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/pretraining/TrainingData/MLP09/Subject_/Subject_None/Subject_None/3500

###

GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/train/BBD_20220829_TrainingData_MLP09_5p0Hz-150000Hz_IsSubject_TimeaNagy_1414rows.csv/MLP09/10


###

# Balanced, randomized CSV data source trained for 1000 seconds
GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/train/BBD_20220829_TrainingData_MLP09_5p0Hz-150000Hz_IsSubject_AndrasFuchs_1000rows.csv/MLP09/1800

###

# Balanced, randomized CSV data source trained for 1800 seconds
GET {{BBD.BodyMonitor.Web_HostAddress}}/MachineLearning/train/BBD_20220829_TrainingData_MLP09_5p0Hz-150000Hz_IsSubject_AndrasFuchs_1000rows.csv/MLP09/1800
