using Microsoft.ML.Data;

namespace BBD.BodyMonitor
{
    /// <summary>
    /// Represents the output structure of an FFT (Fast Fourier Transform) based machine learning model.
    /// This class is intended for internal use within the application.
    /// </summary>
    internal class FftModelOutput
    {
        /// <summary>
        /// Gets or sets the prediction scores generated by the ML.NET model.
        /// The vector type indicates the expected size of the array, typically corresponding to the number of classes or output values of the model.
        /// For example, a `[VectorType(2)]` might represent scores for two classes in a classification task.
        /// </summary>
        [VectorType(2)]
        public float[] Scores { get; set; }
    }
}
